tileset1_data: .incbin "assets/tileset1.bin"
tileset2_data: .incbin "assets/tileset2.bin"
tileset3_data: .incbin "assets/tileset3.bin"
tileset4_data: .incbin "assets/tileset4.bin"
board_data: .incbin "assets/board.bin"
objects_data: .incbin "assets/objects.bin"
board_pal: .incbin "assets/board.pal"
